// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  blockIdsJson: __t.string().name("block_ids_json"),
  adImageUrl: __t.string().name("ad_image_url"),
  adLinkUrl: __t.string().name("ad_link_url"),
  ownerIdentity: __t.string().name("owner_identity"),
  paid: __t.bool(),
  createdAt: __t.u64().name("created_at"),
  expiresAt: __t.u64().name("expires_at"),
});
