// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  keyHash: __t.string().name("key_hash"),
  keyPrefix: __t.string().name("key_prefix"),
  name: __t.string(),
  email: __t.string(),
  credits: __t.u64(),
  totalRequests: __t.u64().name("total_requests"),
  isActive: __t.bool().name("is_active"),
  createdAt: __t.u64().name("created_at"),
  lastUsedAt: __t.u64().name("last_used_at"),
});
