// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  x: __t.i32(),
  y: __t.i32(),
  videoId: __t.string().name("video_id"),
  platform: __t.string(),
  ownerIdentity: __t.string().name("owner_identity"),
  ownerName: __t.string().name("owner_name"),
  likes: __t.u64(),
  dislikes: __t.u64(),
  status: __t.string(),
  adImageUrl: __t.string().name("ad_image_url"),
  adLinkUrl: __t.string().name("ad_link_url"),
  claimedAt: __t.u64().name("claimed_at"),
});
