// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  blockId: __t.u64().name("block_id"),
  userIdentity: __t.string().name("user_identity"),
  userName: __t.string().name("user_name"),
  text: __t.string(),
  createdAt: __t.u64().name("created_at"),
  parentCommentId: __t.option(__t.u64()).name("parent_comment_id"),
  repostOfId: __t.option(__t.u64()).name("repost_of_id"),
  likesCount: __t.u64().name("likes_count"),
  repliesCount: __t.u64().name("replies_count"),
  repostsCount: __t.u64().name("reposts_count"),
});
