// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  contestId: __t.u64().name("contest_id"),
  blockId: __t.u32().name("block_id"),
  ownerIdentity: __t.string().name("owner_identity"),
  ownerName: __t.string().name("owner_name"),
  videoId: __t.string().name("video_id"),
  platform: __t.string(),
  likes: __t.u64(),
  rank: __t.u32(),
  prizeAmount: __t.u64().name("prize_amount"),
});
