// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  userIdentity: __t.string().name("user_identity"),
  txType: __t.string().name("tx_type"),
  amount: __t.i64(),
  balanceAfter: __t.u64().name("balance_after"),
  stripePaymentId: __t.string().name("stripe_payment_id"),
  description: __t.string(),
  createdAt: __t.u64().name("created_at"),
});
