// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  senderIdentity: __t.string().name("sender_identity"),
  recipientIdentity: __t.string().name("recipient_identity"),
  text: __t.string(),
  isRead: __t.bool().name("is_read"),
  createdAt: __t.u64().name("created_at"),
});
