// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  blockId: __t.u64(),
  newVideoId: __t.string(),
  newPlatform: __t.string(),
  newThumbnailUrl: __t.string(),
  newYtViews: __t.u64(),
  newYtLikes: __t.u64(),
};
