// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  slug: __t.string(),
  title: __t.string(),
  description: __t.string(),
  category: __t.string(),
  creatorIdentity: __t.string().name("creator_identity"),
  videoCount: __t.u64().name("video_count"),
  totalLikes: __t.u64().name("total_likes"),
  totalDislikes: __t.u64().name("total_dislikes"),
  totalViews: __t.u64().name("total_views"),
  isActive: __t.bool().name("is_active"),
  createdAt: __t.u64().name("created_at"),
});
