// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AdPlacement = __t.object("AdPlacement", {
  id: __t.u64(),
  topicId: __t.u64(),
  blockIdsJson: __t.string(),
  adImageUrl: __t.string(),
  adLinkUrl: __t.string(),
  ownerIdentity: __t.string(),
  paid: __t.bool(),
  createdAt: __t.u64(),
  expiresAt: __t.u64(),
});
export type AdPlacement = __Infer<typeof AdPlacement>;

export const Block = __t.object("Block", {
  id: __t.u64(),
  topicId: __t.u64(),
  x: __t.i32(),
  y: __t.i32(),
  videoId: __t.string(),
  platform: __t.string(),
  ownerIdentity: __t.string(),
  ownerName: __t.string(),
  likes: __t.u64(),
  dislikes: __t.u64(),
  status: __t.string(),
  ytViews: __t.u64(),
  ytLikes: __t.u64(),
  thumbnailUrl: __t.string(),
  adImageUrl: __t.string(),
  adLinkUrl: __t.string(),
  claimedAt: __t.u64(),
});
export type Block = __Infer<typeof Block>;

export const ClerkIdentityMap = __t.object("ClerkIdentityMap", {
  clerkUserId: __t.string(),
  spacetimedbIdentity: __t.string(),
});
export type ClerkIdentityMap = __Infer<typeof ClerkIdentityMap>;

export const Comment = __t.object("Comment", {
  id: __t.u64(),
  blockId: __t.u64(),
  userIdentity: __t.string(),
  userName: __t.string(),
  text: __t.string(),
  createdAt: __t.u64(),
  parentCommentId: __t.option(__t.u64()),
  repostOfId: __t.option(__t.u64()),
  likesCount: __t.u64(),
  repliesCount: __t.u64(),
  repostsCount: __t.u64(),
});
export type Comment = __Infer<typeof Comment>;

export const CommentLike = __t.object("CommentLike", {
  id: __t.u64(),
  commentId: __t.u64(),
  userIdentity: __t.string(),
  createdAt: __t.u64(),
});
export type CommentLike = __Infer<typeof CommentLike>;

export const Contest = __t.object("Contest", {
  id: __t.u64(),
  startAt: __t.u64(),
  endAt: __t.u64(),
  prizePool: __t.u64(),
  status: __t.string(),
});
export type Contest = __Infer<typeof Contest>;

export const ContestWinner = __t.object("ContestWinner", {
  id: __t.u64(),
  contestId: __t.u64(),
  blockId: __t.u64(),
  ownerIdentity: __t.string(),
  ownerName: __t.string(),
  videoId: __t.string(),
  platform: __t.string(),
  likes: __t.u64(),
  rank: __t.u32(),
  prizeAmount: __t.u64(),
});
export type ContestWinner = __Infer<typeof ContestWinner>;

export const CreditTransactionLog = __t.object("CreditTransactionLog", {
  id: __t.u64(),
  userIdentity: __t.string(),
  txType: __t.string(),
  amount: __t.i64(),
  balanceAfter: __t.u64(),
  stripePaymentId: __t.string(),
  description: __t.string(),
  createdAt: __t.u64(),
});
export type CreditTransactionLog = __Infer<typeof CreditTransactionLog>;

export const DirectMessage = __t.object("DirectMessage", {
  id: __t.u64(),
  senderIdentity: __t.string(),
  recipientIdentity: __t.string(),
  text: __t.string(),
  isRead: __t.bool(),
  createdAt: __t.u64(),
});
export type DirectMessage = __Infer<typeof DirectMessage>;

export const DislikeRecord = __t.object("DislikeRecord", {
  id: __t.u64(),
  blockId: __t.u64(),
  userIdentity: __t.string(),
  createdAt: __t.u64(),
});
export type DislikeRecord = __Infer<typeof DislikeRecord>;

export const LikeRecord = __t.object("LikeRecord", {
  id: __t.u64(),
  blockId: __t.u64(),
  userIdentity: __t.string(),
  createdAt: __t.u64(),
});
export type LikeRecord = __Infer<typeof LikeRecord>;

export const Notification = __t.object("Notification", {
  id: __t.u64(),
  recipientIdentity: __t.string(),
  actorIdentity: __t.string(),
  actorName: __t.string(),
  notificationType: __t.string(),
  blockId: __t.u64(),
  commentId: __t.u64(),
  isRead: __t.bool(),
  createdAt: __t.u64(),
});
export type Notification = __Infer<typeof Notification>;

export const Topic = __t.object("Topic", {
  id: __t.u64(),
  slug: __t.string(),
  title: __t.string(),
  description: __t.string(),
  category: __t.string(),
  creatorIdentity: __t.string(),
  videoCount: __t.u64(),
  totalLikes: __t.u64(),
  totalDislikes: __t.u64(),
  totalViews: __t.u64(),
  isActive: __t.bool(),
  createdAt: __t.u64(),
  taxonomyNodeId: __t.option(__t.u64()),
});
export type Topic = __Infer<typeof Topic>;

export const TopicModerator = __t.object("TopicModerator", {
  id: __t.u64(),
  topicId: __t.u64(),
  identity: __t.string(),
  role: __t.string(),
  status: __t.string(),
  grantedBy: __t.string(),
  createdAt: __t.u64(),
});
export type TopicModerator = __Infer<typeof TopicModerator>;

export const TopicModeratorApplication = __t.object("TopicModeratorApplication", {
  id: __t.u64(),
  topicId: __t.u64(),
  applicantIdentity: __t.string(),
  message: __t.string(),
  status: __t.string(),
  reviewedBy: __t.string(),
  createdAt: __t.u64(),
  reviewedAt: __t.u64(),
});
export type TopicModeratorApplication = __Infer<typeof TopicModeratorApplication>;

export const TopicTaxonomyNode = __t.object("TopicTaxonomyNode", {
  id: __t.u64(),
  slug: __t.string(),
  name: __t.string(),
  parentId: __t.option(__t.u64()),
  path: __t.string(),
  depth: __t.u32(),
  isActive: __t.bool(),
  createdAt: __t.u64(),
});
export type TopicTaxonomyNode = __Infer<typeof TopicTaxonomyNode>;

export const TransactionLog = __t.object("TransactionLog", {
  id: __t.u64(),
  txType: __t.string(),
  amount: __t.u64(),
  fromIdentity: __t.string(),
  toIdentity: __t.string(),
  stripeId: __t.string(),
  description: __t.string(),
  createdAt: __t.u64(),
});
export type TransactionLog = __Infer<typeof TransactionLog>;

export const UserProfile = __t.object("UserProfile", {
  identity: __t.string(),
  clerkUserId: __t.string(),
  username: __t.string(),
  displayName: __t.string(),
  email: __t.string(),
  stripeAccountId: __t.string(),
  totalEarnings: __t.u64(),
  credits: __t.u64(),
  isAdmin: __t.bool(),
  createdAt: __t.u64(),
});
export type UserProfile = __Infer<typeof UserProfile>;

