// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AdPlacement = __t.object("AdPlacement", {
  id: __t.u64(),
  blockIdsJson: __t.string(),
  adImageUrl: __t.string(),
  adLinkUrl: __t.string(),
  ownerIdentity: __t.string(),
  paid: __t.bool(),
  createdAt: __t.u64(),
  expiresAt: __t.u64(),
});
export type AdPlacement = __Infer<typeof AdPlacement>;

export const Block = __t.object("Block", {
  id: __t.u32(),
  x: __t.i32(),
  y: __t.i32(),
  videoId: __t.string(),
  platform: __t.string(),
  ownerIdentity: __t.string(),
  ownerName: __t.string(),
  likes: __t.u64(),
  dislikes: __t.u64(),
  status: __t.string(),
  adImageUrl: __t.string(),
  adLinkUrl: __t.string(),
  claimedAt: __t.u64(),
});
export type Block = __Infer<typeof Block>;

export const ClerkIdentityMap = __t.object("ClerkIdentityMap", {
  clerkUserId: __t.string(),
  spacetimedbIdentity: __t.string(),
});
export type ClerkIdentityMap = __Infer<typeof ClerkIdentityMap>;

export const Comment = __t.object("Comment", {
  id: __t.u64(),
  blockId: __t.u32(),
  userIdentity: __t.string(),
  userName: __t.string(),
  text: __t.string(),
  createdAt: __t.u64(),
});
export type Comment = __Infer<typeof Comment>;

export const Contest = __t.object("Contest", {
  id: __t.u64(),
  startAt: __t.u64(),
  endAt: __t.u64(),
  prizePool: __t.u64(),
  status: __t.string(),
});
export type Contest = __Infer<typeof Contest>;

export const ContestWinner = __t.object("ContestWinner", {
  id: __t.u64(),
  contestId: __t.u64(),
  blockId: __t.u32(),
  ownerIdentity: __t.string(),
  ownerName: __t.string(),
  videoId: __t.string(),
  platform: __t.string(),
  likes: __t.u64(),
  rank: __t.u32(),
  prizeAmount: __t.u64(),
});
export type ContestWinner = __Infer<typeof ContestWinner>;

export const DislikeRecord = __t.object("DislikeRecord", {
  id: __t.u64(),
  blockId: __t.u32(),
  userIdentity: __t.string(),
  createdAt: __t.u64(),
});
export type DislikeRecord = __Infer<typeof DislikeRecord>;

export const LikeRecord = __t.object("LikeRecord", {
  id: __t.u64(),
  blockId: __t.u32(),
  userIdentity: __t.string(),
  createdAt: __t.u64(),
});
export type LikeRecord = __Infer<typeof LikeRecord>;

export const TransactionLog = __t.object("TransactionLog", {
  id: __t.u64(),
  txType: __t.string(),
  amount: __t.u64(),
  fromIdentity: __t.string(),
  toIdentity: __t.string(),
  stripeId: __t.string(),
  description: __t.string(),
  createdAt: __t.u64(),
});
export type TransactionLog = __Infer<typeof TransactionLog>;

export const UserProfile = __t.object("UserProfile", {
  identity: __t.string(),
  clerkUserId: __t.string(),
  username: __t.string(),
  displayName: __t.string(),
  email: __t.string(),
  stripeAccountId: __t.string(),
  totalEarnings: __t.u64(),
  isAdmin: __t.bool(),
  createdAt: __t.u64(),
});
export type UserProfile = __Infer<typeof UserProfile>;

