// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  bio: __t.string(),
  location: __t.string(),
  websiteUrl: __t.string(),
  socialX: __t.string(),
  socialYoutube: __t.string(),
  socialTiktok: __t.string(),
  socialInstagram: __t.string(),
};
