// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  reporterIdentity: __t.string().name("reporter_identity"),
  reportedIdentity: __t.string().name("reported_identity"),
  reason: __t.string(),
  description: __t.string(),
  status: __t.string(),
  reviewedBy: __t.string().name("reviewed_by"),
  createdAt: __t.u64().name("created_at"),
  reviewedAt: __t.u64().name("reviewed_at"),
});
