// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.string().primaryKey(),
  displayName: __t.string().name("display_name"),
  email: __t.string(),
  stripeAccountId: __t.string().name("stripe_account_id"),
  totalEarnings: __t.u64().name("total_earnings"),
  isAdmin: __t.bool().name("is_admin"),
  createdAt: __t.u64().name("created_at"),
});
