// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddCommentReducer from "../add_comment_reducer";
import AddCreditsReducer from "../add_credits_reducer";
import ApplyTopicModeratorReducer from "../apply_topic_moderator_reducer";
import BackfillTopicTaxonomyFromCategoriesReducer from "../backfill_topic_taxonomy_from_categories_reducer";
import ClaimBlockInTopicReducer from "../claim_block_in_topic_reducer";
import ClearAllBlocksReducer from "../clear_all_blocks_reducer";
import CreateContestReducer from "../create_contest_reducer";
import CreateTopicReducer from "../create_topic_reducer";
import CreateTopicTaxonomyNodeReducer from "../create_topic_taxonomy_node_reducer";
import DeleteCommentReducer from "../delete_comment_reducer";
import DeleteTopicReducer from "../delete_topic_reducer";
import DevClearAllUsersReducer from "../dev_clear_all_users_reducer";
import DevSeedTopicReducer from "../dev_seed_topic_reducer";
import DevSetAdminReducer from "../dev_set_admin_reducer";
import DislikeVideoReducer from "../dislike_video_reducer";
import FinalizeContestReducer from "../finalize_contest_reducer";
import IncrementTopicViewsReducer from "../increment_topic_views_reducer";
import LikeVideoReducer from "../like_video_reducer";
import MarkAdPaidReducer from "../mark_ad_paid_reducer";
import PlaceAdReducer from "../place_ad_reducer";
import RebalanceTopicReducer from "../rebalance_topic_reducer";
import RegisterUserReducer from "../register_user_reducer";
import RemoveAdReducer from "../remove_ad_reducer";
import RemoveTopicModeratorReducer from "../remove_topic_moderator_reducer";
import ReviewTopicModeratorApplicationReducer from "../review_topic_moderator_application_reducer";
import SeedAdsReducer from "../seed_ads_reducer";
import SeedDataReducer from "../seed_data_reducer";
import ServerDeleteUserReducer from "../server_delete_user_reducer";
import ServerUpdateProfileReducer from "../server_update_profile_reducer";
import SetAdminReducer from "../set_admin_reducer";
import SetTopicTaxonomyReducer from "../set_topic_taxonomy_reducer";
import SpendCreditsReducer from "../spend_credits_reducer";
import StoreClerkMappingReducer from "../store_clerk_mapping_reducer";
import UnclaimBlockReducer from "../unclaim_block_reducer";
import UndislikeVideoReducer from "../undislike_video_reducer";
import UnlikeVideoReducer from "../unlike_video_reducer";
import UpdateProfileReducer from "../update_profile_reducer";
import UpdateStripeAccountReducer from "../update_stripe_account_reducer";
import UpdateTopicReducer from "../update_topic_reducer";

export type AddCommentParams = __Infer<typeof AddCommentReducer>;
export type AddCreditsParams = __Infer<typeof AddCreditsReducer>;
export type ApplyTopicModeratorParams = __Infer<typeof ApplyTopicModeratorReducer>;
export type BackfillTopicTaxonomyFromCategoriesParams = __Infer<typeof BackfillTopicTaxonomyFromCategoriesReducer>;
export type ClaimBlockInTopicParams = __Infer<typeof ClaimBlockInTopicReducer>;
export type ClearAllBlocksParams = __Infer<typeof ClearAllBlocksReducer>;
export type CreateContestParams = __Infer<typeof CreateContestReducer>;
export type CreateTopicParams = __Infer<typeof CreateTopicReducer>;
export type CreateTopicTaxonomyNodeParams = __Infer<typeof CreateTopicTaxonomyNodeReducer>;
export type DeleteCommentParams = __Infer<typeof DeleteCommentReducer>;
export type DeleteTopicParams = __Infer<typeof DeleteTopicReducer>;
export type DevClearAllUsersParams = __Infer<typeof DevClearAllUsersReducer>;
export type DevSeedTopicParams = __Infer<typeof DevSeedTopicReducer>;
export type DevSetAdminParams = __Infer<typeof DevSetAdminReducer>;
export type DislikeVideoParams = __Infer<typeof DislikeVideoReducer>;
export type FinalizeContestParams = __Infer<typeof FinalizeContestReducer>;
export type IncrementTopicViewsParams = __Infer<typeof IncrementTopicViewsReducer>;
export type LikeVideoParams = __Infer<typeof LikeVideoReducer>;
export type MarkAdPaidParams = __Infer<typeof MarkAdPaidReducer>;
export type PlaceAdParams = __Infer<typeof PlaceAdReducer>;
export type RebalanceTopicParams = __Infer<typeof RebalanceTopicReducer>;
export type RegisterUserParams = __Infer<typeof RegisterUserReducer>;
export type RemoveAdParams = __Infer<typeof RemoveAdReducer>;
export type RemoveTopicModeratorParams = __Infer<typeof RemoveTopicModeratorReducer>;
export type ReviewTopicModeratorApplicationParams = __Infer<typeof ReviewTopicModeratorApplicationReducer>;
export type SeedAdsParams = __Infer<typeof SeedAdsReducer>;
export type SeedDataParams = __Infer<typeof SeedDataReducer>;
export type ServerDeleteUserParams = __Infer<typeof ServerDeleteUserReducer>;
export type ServerUpdateProfileParams = __Infer<typeof ServerUpdateProfileReducer>;
export type SetAdminParams = __Infer<typeof SetAdminReducer>;
export type SetTopicTaxonomyParams = __Infer<typeof SetTopicTaxonomyReducer>;
export type SpendCreditsParams = __Infer<typeof SpendCreditsReducer>;
export type StoreClerkMappingParams = __Infer<typeof StoreClerkMappingReducer>;
export type UnclaimBlockParams = __Infer<typeof UnclaimBlockReducer>;
export type UndislikeVideoParams = __Infer<typeof UndislikeVideoReducer>;
export type UnlikeVideoParams = __Infer<typeof UnlikeVideoReducer>;
export type UpdateProfileParams = __Infer<typeof UpdateProfileReducer>;
export type UpdateStripeAccountParams = __Infer<typeof UpdateStripeAccountReducer>;
export type UpdateTopicParams = __Infer<typeof UpdateTopicReducer>;

