// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddCommentReducer from "../add_comment_reducer";
import ClaimBlockReducer from "../claim_block_reducer";
import ClearAllBlocksReducer from "../clear_all_blocks_reducer";
import CreateContestReducer from "../create_contest_reducer";
import DeleteCommentReducer from "../delete_comment_reducer";
import DislikeVideoReducer from "../dislike_video_reducer";
import FinalizeContestReducer from "../finalize_contest_reducer";
import LikeVideoReducer from "../like_video_reducer";
import MarkAdPaidReducer from "../mark_ad_paid_reducer";
import PlaceAdReducer from "../place_ad_reducer";
import RebalanceLayoutReducer from "../rebalance_layout_reducer";
import RegisterUserReducer from "../register_user_reducer";
import RemoveAdReducer from "../remove_ad_reducer";
import SeedAdsReducer from "../seed_ads_reducer";
import SeedDataReducer from "../seed_data_reducer";
import SetAdminReducer from "../set_admin_reducer";
import UnclaimBlockReducer from "../unclaim_block_reducer";
import UndislikeVideoReducer from "../undislike_video_reducer";
import UnlikeVideoReducer from "../unlike_video_reducer";
import UpdateStripeAccountReducer from "../update_stripe_account_reducer";

export type AddCommentParams = __Infer<typeof AddCommentReducer>;
export type ClaimBlockParams = __Infer<typeof ClaimBlockReducer>;
export type ClearAllBlocksParams = __Infer<typeof ClearAllBlocksReducer>;
export type CreateContestParams = __Infer<typeof CreateContestReducer>;
export type DeleteCommentParams = __Infer<typeof DeleteCommentReducer>;
export type DislikeVideoParams = __Infer<typeof DislikeVideoReducer>;
export type FinalizeContestParams = __Infer<typeof FinalizeContestReducer>;
export type LikeVideoParams = __Infer<typeof LikeVideoReducer>;
export type MarkAdPaidParams = __Infer<typeof MarkAdPaidReducer>;
export type PlaceAdParams = __Infer<typeof PlaceAdReducer>;
export type RebalanceLayoutParams = __Infer<typeof RebalanceLayoutReducer>;
export type RegisterUserParams = __Infer<typeof RegisterUserReducer>;
export type RemoveAdParams = __Infer<typeof RemoveAdReducer>;
export type SeedAdsParams = __Infer<typeof SeedAdsReducer>;
export type SeedDataParams = __Infer<typeof SeedDataReducer>;
export type SetAdminParams = __Infer<typeof SetAdminReducer>;
export type UnclaimBlockParams = __Infer<typeof UnclaimBlockReducer>;
export type UndislikeVideoParams = __Infer<typeof UndislikeVideoReducer>;
export type UnlikeVideoParams = __Infer<typeof UnlikeVideoReducer>;
export type UpdateStripeAccountParams = __Infer<typeof UpdateStripeAccountReducer>;

